add namu command
team-play-together/together-bot pull request #51
Opened 2021-04-11 11:12 UTC by minseungkang

나무위키 검색 커맨드

% -> %25
\  -> %5C
공백 -> %20

2021-04-11 16:35 UTC, WraithKim requested changes
직접 문자열을 변환하는거 보다 urllib.parse을 쓰는게 안전해보이는데...?

2021-04-11 17:43 UTC, WraithKim requested changes

2021-04-11 17:43 UTC, WraithKim commented on together_bot/commands.py
> +    query = " ".join(args)
[공백 포함 명령어 매개변수 받는 법](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#keyword-only-arguments)  
이거 쓰면 굳이 join 할 필요 없음

2021-04-11 18:06 UTC, WraithKim requested changes
처리할 특수문자 추가 필요.

2021-04-11 18:06 UTC, WraithKim commented on together_bot/commands.py
> +    namu_wiki_escape_code_dict = {"%": "%25", "\\": "%5C"}
이왕이면 특수문자 전부 처리하는게 좋을 듯
[percent-encoding special characters](https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding)  
단, 나무위키에서 다음 문자는 인코딩 하지 않음.
|문자|코드|
-----|-----
|\:|%3A|
|/|%2F|
|'|%27|
|*|%2A|
|,|%2C|

2021-04-12 00:42 UTC, minseungkang commented on together_bot/commands.py
> +    namu_wiki_escape_code_dict = {"%": "%25", "\\": "%5C"}
![image](https://user-images.githubusercontent.com/8479237/114327151-d65e1880-9b72-11eb-9185-3b4091c2aff0.png)
 저 문자들 다 url 창에 검색해보면 정상적으로 찾아가도록 되어있음.
https://namu.wiki/w/,
https://namu.wiki/w//
https://namu.wiki/w/'
https://namu.wiki/w/*
https://namu.wiki/w/,

2021-04-12 00:43 UTC, minseungkang commented on together_bot/commands.py
> +    namu_wiki_escape_code_dict = {"%": "%25", "\\": "%5C"}
하나하나 확인해봤는데, #랑 ?은 자동 변환처리되어서 ?랑 #에 대해서만 추가해주면 될 듯. 그 외엔 정상 동작

2021-04-12 00:44 UTC, minseungkang commented
> 직접 문자열을 변환하는거 보다 urllib.parse을 쓰는게 안전해보이는데...?

urllib.parse에서 파싱 해주는것과 나무위키에서 escape sequence 파싱하는게 다르게 돌아가더라

2021-04-12 04:16 UTC, WraithKim commented on together_bot/commands.py
> +    namu_wiki_escape_code_dict = {"%": "%25", "\\": "%5C"}
[나무위키 하이퍼링크](https://namu.wiki/w/%EB%82%98%EB%AC%B4%EC%9C%84%ED%82%A4:%EB%AC%B8%EB%B2%95%20%EB%8F%84%EC%9B%80%EB%A7%90/%EC%8B%AC%ED%99%94#s-3.2) 이게 더 관련있는 얘기일 수도 있겠넴... 저녁에 확인해보지뭐

2021-04-12 05:08 UTC, minseungkang commented on together_bot/commands.py
> +    namu_wiki_escape_code_dict = {"%": "%25", "\\": "%5C"}
저건 나무위키 문서 내에서 링크 걸 때의 주의사항인 것 같음. url이랑은 관계없는듯?

2021-04-12 09:08 UTC, WraithKim commented on together_bot/commands.py
> +    namu_wiki_escape_code_dict = {"%": "%25", "\\": "%5C"}
그렇네 URL 해석할 때는 문제 없는듯

2021-04-12 16:07 UTC, WraithKim approved these changes

2021-04-12 16:10 UTC, WraithKim commented
@lyuha 별 의견 없으면 내가 머지함.

2021-04-12 22:16 UTC, lyuha approved these changes

2021-04-13 00:56 UTC, minseungkang commented
뭐야 난 머지가안되네

2021-04-13 00:57 UTC, merged