비속어 리스트 업데이트 및 관련 스크립트 수정
team-play-together/together-bot pull request #52
Opened 2021-04-13 10:27 UTC by WraithKim

* 비속어 리스트에서 일부 단어 수정 및 삭제
  * 도박, 인터넷 광고 관련 단어 제거
  * 선정적이거나 폭력적인 단어와 관련이 적은 단어 제거
  * 주관적인 수정이므로 추후 수정을 할 수 있음.
* 비속어 리스트의 단어 구분을 쉼표에서 LF로 변경
  * 대부분의 파일 diff가 line 기반임. 수정된 단어를 추적하기 쉽게 이를
 따라감.
* `fword_list_refinery.py` 가 명령어 인자를 받도록 수정
* 비속어 명령어가 *표 대신 스포일러 처리로 비속어를 가리도록 수정
  * 어떤 단어가 필터링 되었는지 확인하기 쉽도록 함.

2021-04-13 10:35 UTC, WraithKim commented
@lyuha 
돌아가는지 + 문법적인 똥은 없는지만 확인해주든지 아니면 걍 스킵해도 됨.
비속어 리스트는.... 5천개 비속어 읽으니까 나도 어질어질함...

2021-04-15 14:03 UTC, lyuha requested changes
https://github.com/team-play-together/together-bot/blob/747cf6e50e4c7da70e9a820463345040a1b4d60e/together_bot/fword.py#L29
`is_on` arg가 없을 수도 있으니 이 부분 수정.

2021-04-16 18:32 UTC, WraithKim commented
욕설 리스트 전체적으로 갈아엎어야 될듯.... ㄹㅇ 싹을 쳐내고 커밋한다.

2021-04-17 02:34 UTC, lyuha approved these changes

2021-04-17 06:10 UTC, WraithKim commented on together_bot/fword.py
>          char_list = [*content]
[Additional Unpacking Generalizations](https://www.python.org/dev/peps/pep-0448/)  
단점으로 argument 순서에 따른 타입 추론 문제 같은게 있어서 겉으론 쉬워보여도 상황에 따라선 더 어려운 문법이라고 함.
그래도 여기 예시로 list(s)보단 [*s]로 쓰는게 더 깔끔하다고 생각해서 3.5 부터 추가한거라니깐... 난 이걸 따를랭.

2021-04-17 07:12 UTC, WraithKim commented
> 욕설 리스트 전체적으로 갈아엎어야 될듯.... ㄹㅇ 싹을 쳐내고 커밋한다.

힘들어 나중에 커밋으로 묶을래;;;

2021-04-17 07:32 UTC, merged