키워드를 등록해서 입력된 keyword가 있을 때 자신에게 mention하는 기능 추가
team-play-together/together-bot pull request #54
Opened 2021-04-22 06:37 UTC by kangyb1014

키워드를 등록해서 입력된 keyword가 있을 때 자신에게 mention하는 기능 추가

!keyword help : 이 명령어를 출력합니다.
!keyword list : 자신에게 등록된 키워드를 모두 보여줍니다.
!keyword add KEYWORD : 자신의 키워드에 KEYWORD를 등록합니다 .
!keyword delete KEYWORD : 자신에게 등록된 키워드 중 KEYWORD를 삭제합니다.

![keyword_mention](https://user-images.githubusercontent.com/26961908/115667231-91ab5c00-a380-11eb-87d3-f080ce3d038e.gif)

2021-04-22 09:38 UTC, WraithKim requested changes
굳이 언급 안한 변경 요청 사항
* 개행(함수는 2개행 뭐 이런 규칙 있음.)
* 아무 이유 없이 공백 두개 넣은거. 공백 안 넣은거...(얼탱이 없겠지만 공백도 PEP에 적혀있음)
=> 쓰고 있는 IDE에서 lint 돌려보든지 아니면 프로젝트 루트 디렉토리에서 `$poetry run flake8` 돌려보셈.

kmp는 리뷰 안해둠. 나도 kmp 몰라서 공부하고 와야돼;;;
그리고 내 리뷰가 잘못되었을 수도 있음. (류하가 알아서 하겠지)

2021-04-22 09:38 UTC, WraithKim commented on together_bot/keyword.py
> +        # 중복 키워드가 없을 경우 키워드 등록
중복 제거를 하고 싶고, keyword 리스트의 순서를 유지할 필요가 없다면 list보다 set을 쓰는게 더 적합하지 않을까?
그리고 빠른 검색을 하고 싶다고 `keywordsByUserID`와 `usersBykeyword`라는 서로 중복된 데이터가 있는데,
검색하는 방법을 Big-O notation으로 생각하면 결국 O(n)이라 같아보임. 그래서 `keywordsByUserID`가 없어도 되지 않을까?

가 내 생각.

2021-04-22 09:38 UTC, WraithKim commented on together_bot/keyword.py
> +        if len(message.content) > Keyword.MAX_TARGET_LENGTH:
문자열 길다고 생각보다 그렇게 딜레이 안걸리는뎀... 아무리 free tier지만 현대 컴퓨팅파워를 믿으셈.
(어차피 느리면 류하가 돈 더주고 헤로쿠 업뎃할거임)

2021-04-22 09:38 UTC, WraithKim commented on together_bot/keyword.py
> +            if self.getUserListBykeyword(keyword) and Keyword.kmp(
https://github.com/python/cpython/blob/master/Objects/stringlib/fastsearch.h
python in 연산자는 substring 검색에도 쓸 수 있고, kmp는 아니지만 비슷한 알고리즘을 씀. 그래서 보통은 걍 `{substring} in {string}`을 쓴다.

뭐 토이프로젝트니까 "그거 삭제하세요!" 같은 소리는 아님. 대신 위의 링크처럼 이런 알고리즘도 있다 정도는 알아두면 좋을... 지도?

2021-04-22 09:38 UTC, WraithKim commented on together_bot/keyword.py
> +        for mention in mentionList:
이건 디스코드 API 호출이라 메세지 여러개 보내면 봇이 눈에 띄게 딜레이 걸림.
하나의 메세지로 묶든지 멘션 키워드 하나만 언급하든지 하는게 좋을듯.

2021-04-22 13:13 UTC, WraithKim requested changes
kmp 이해하다가 머리 터졌다. 그나마 이거는 수정해야 할 듯

2021-04-22 13:23 UTC, kangyb1014 commented on together_bot/keyword.py
> +    async def add(self, ctx: commands.Context, keyword:str):
키워드는 단일 단어로 구성된다고 생각하고, 여러 단어로 이루어진 키워드는 고려대상이 아니어서 따로 구현하지는 않았습니다.
단 `keyword add KEYWORD1 KEYWORD2 KEYWORD3...` 와 같이 여러 키워드를 한 번에 등록하는 기능은 고려 중

2021-04-23 05:38 UTC, WraithKim commented on together_bot/keyword.py
> +    async def add(self, ctx: commands.Context, keyword:str):
그럼 help에 명시를 해두는게 좋을 지도
ex) `keyword add KEYWORD: KEYWORD - 맨션할 키워드(공백 허용안함)`

2021-04-23 06:38 UTC, kangyb1014 commented on together_bot/keyword.py
> +        for mention in mentionList:
키워드를 1개만 언급할 경우 키워드에 대해 일관성이 떨어질 것 같아서 모든 키워드를 알려주는 방향으로 유지하려고 하고요.
키워드+유저를 정리해서 하나의 메시지로 묶어서 send하려고 합니다.
mention push알림은 메시지의 개수만큼 발생해서.. mention이 과도하게 발생하는 문제를 피할 수 있을 듯..?

2021-04-23 06:45 UTC, kangyb1014 commented on together_bot/keyword.py
> +        if message.content.startswith("!"):
봇 관련 채팅을 무시하려는 의도여서 `context.valid`로 수정하는 게 맞고, 다음 PR에 반영하겠습니다

2021-04-23 09:01 UTC, kangyb1014 commented on together_bot/keyword.py
> +        await ctx.send(f'`{ctx.author.display_name}`' + ' 사용자에게 등록된 키워드 : ' + ', '.join(f'`{keyword}`' for keyword in keywordsByUserID))
작성 당시에 f-string + join + 줄바꿈으로 코드가 뒤죽박죽이 되었던 것 같고... 다음과 같이 변경
``` 
keywordsByUserID = self.getKeywordsByUserID(ctx.author.id)
keywordsMsg = ", ".join(f"`{keyword}`" for keyword in keywordsByUserID)
msg = f"`{ctx.author.display_name}` 사용자에게 등록된 키워드: {keywordsMsg}"
await ctx.send(msg)

2021-04-23 14:18 UTC, lyuha requested changes
## PEP 8

PEP8 변수와 함수 선언은 snake_case로 써야한다.

[PEP8 Function and Variable Names](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names)

## 사용 이슈

만약에 키워드가 code 섹션 안에 있다면? 이건 호출할 것인가?

## help 개선

brief 내용은 help에도 있어야 한다. 현재는 help만 쳤을 때 이 커맨드가 무엇을 하는지 알 수 없다.

2021-04-23 14:18 UTC, lyuha commented on together_bot/keyword.py
> +    async def add(self, ctx: commands.Context, keyword: str):
keyword에 아무것도 넣지 않는다면?
keyword에 공백 문자같은 걸 추가하면 어떻게 동작하는가?

2021-04-25 08:44 UTC, WraithKim requested changes

2021-04-25 08:44 UTC, WraithKim commented on together_bot/keyword.py
> +        self.keywordDict = {}
둘이 서로 종속되어 있는거 같은데 하나의 클래스로 분리하는게 더 깔끔할 거 같음.
그러면 명령어 클래스에 `addToDict()`, `deleteFromDict()`같은 함수가 있어서 복잡해 보이는 것도 적어질듯.

2021-04-25 08:44 UTC, WraithKim commented on together_bot/keyword.py
> +            )
이런 부분도 만약 keyword와 userID의 관계를 보관하는 클래스로 구분했다면 delete 명령어에서 호출할 건,
ex) `keyword_userID_pairs.delete_keyword(keyword)` 정도로 끝났을거임.

2021-04-25 08:44 UTC, WraithKim commented on together_bot/keyword.py
> +        await message.channel.send(mentionText)
이거 한 메세지 안에 여러명을 맨션할 경우를 위해 list 형태로 저장하는 것 같은데,
mentions가 list[dict(keyword userid)]라면 결국 여러 키워드에 자기 이름이 있다면 여러번 찍혀 있을 거임.

그리고 메세지가 길어질 수 있어서 텍스트 채널에 올리는 건 적절하지 않을 거 같음. 그렇다면,
1. 텍스트 채널에 올릴거면 메세지를 줄이고, (ex. 누굴 멘션할 것인지만 들어있는 거)
2. 각자에게 DM을 보내도 됨. "[호출한 메세지 링크] - 이러이러한 키워드가 포함되어 있어서 당신이 호출됨."

2021-04-25 08:50 UTC, WraithKim commented
> ## help 개선
> brief 내용은 help에도 있어야 한다. 현재는 help만 쳤을 때 이 커맨드가 무엇을 하는지 알 수 없다.
이건 기존 명령어도 지켜지지 않고 있긴 함. 지금 brief는 상위 커멘드에서 help를 쳐야 보이고, 서브커맨드 설명에 가까움,
help는 해당 명령어를 사용하는 방법, 즉 parameters에 대한 설명에 가깝게 적혀있음.

나중에 기존 명령어들도 반영해둬야 겠다.

2021-06-03 22:56 UTC, closed without merging