Time 명령어 경계값 관련 테스트 추가 #63
team-play-together/together-bot pull request #66
Opened 2021-06-12 12:10 UTC by WraithKim

- `dateutil.parser`를 사용하는 함수에 대한 예외 처리 추가
    - `ValueError`, `OSError`, `OverflowError`, `TypeError`,
    `ParserError`
- `datetime.fromtimestamp()`를 사용하는 함수에 대한 예외 처리 추가
    - `OverflowError`, `OSError`

2021-06-13 15:13 UTC, lyuha commented
Docker에서 pytest 실행 시 테스트 실패

<details>
<summary>출력</summary>

```log
platform linux -- Python 3.9.5, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /workspaces/together-bot
collected 24 items                                                                                                                                                                                                                                                             

tests/test_time.py .....FF......FF......FF                                                                                                                                                                                                                               [ 95%]
tests/test_together_bot.py .                                                                                                                                                                                                                                             [100%]

=================================================================================================================================== FAILURES ===================================================================================================================================
__________________________________________________________________________________________________________________________ test_from_kst_time_string ___________________________________________________________________________________________________________________________

    def test_from_kst_time_string():
>       assert from_kst_time_string("2020-11-30 09:59PM") == datetime(
            2020, 11, 30, 21, 59, tzinfo=tz_kst
        )
E       AssertionError: assert datetime.datetime(2020, 12, 1, 6, 59, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400))) == datetime.datetime(2020, 11, 30, 21, 59, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400)))
E        +  where datetime.datetime(2020, 12, 1, 6, 59, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400))) = from_kst_time_string('2020-11-30 09:59PM')
E        +  and   datetime.datetime(2020, 11, 30, 21, 59, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400))) = datetime(2020, 11, 30, 21, 59, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400)))

tests/test_time.py:47: AssertionError
___________________________________________________________________________________________________________________ test_from_kst_time_string_with_ignoretz ____________________________________________________________________________________________________________________

    def test_from_kst_time_string_with_ignoretz():
>       assert from_kst_time_string("2021-03-31 17:17:01+00:00") == datetime(
            2021, 3, 31, 17, 17, 1, tzinfo=tz_kst
        )
E       AssertionError: assert datetime.datetime(2021, 4, 1, 2, 17, 1, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400))) == datetime.datetime(2021, 3, 31, 17, 17, 1, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400)))
E        +  where datetime.datetime(2021, 4, 1, 2, 17, 1, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400))) = from_kst_time_string('2021-03-31 17:17:01+00:00')
E        +  and   datetime.datetime(2021, 3, 31, 17, 17, 1, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400))) = datetime(2021, 3, 31, 17, 17, 1, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400)))

tests/test_time.py:54: AssertionError
________________________________________________________________________________________________________ test_kst_time_overflow_by_timezone_change[0001-01-01T00:00:00] ________________________________________________________________________________________________________

kst_time = '0001-01-01T00:00:00'

    @pytest.mark.parametrize(
        "kst_time",
        [
            datetime.min.isoformat(),
            datetime.max.isoformat(),
        ],
    )
    def test_kst_time_overflow_by_timezone_change(kst_time):
        with pytest.raises(OSError):
>           dt = from_kst_time_string(kst_time)

tests/test_time.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

kst_time = '0001-01-01T00:00:00'

    def from_kst_time_string(kst_time: str):
>       return parse(kst_time, ignoretz=True).astimezone(tz_kst)
E       ValueError: year 0 is out of range

together_bot/time.py:84: ValueError
____________________________________________________________________________________________________ test_kst_time_overflow_by_timezone_change[9999-12-31T23:59:59.999999] _____________________________________________________________________________________________________

kst_time = '9999-12-31T23:59:59.999999'

    @pytest.mark.parametrize(
        "kst_time",
        [
            datetime.min.isoformat(),
            datetime.max.isoformat(),
        ],
    )
    def test_kst_time_overflow_by_timezone_change(kst_time):
        with pytest.raises(OSError):
>           dt = from_kst_time_string(kst_time)

tests/test_time.py:84: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

kst_time = '9999-12-31T23:59:59.999999'

    def from_kst_time_string(kst_time: str):
>       return parse(kst_time, ignoretz=True).astimezone(tz_kst)
E       OverflowError: date value out of range

together_bot/time.py:84: OverflowError
_________________________________________________________________________________________________________________________ test_wrong_timestamp[-43201] _________________________________________________________________________________________________________________________

timestamp = -43201

    @pytest.mark.parametrize(
        "timestamp",
        [
            2 ** 60,
            -43201,
            1523443804214.0,
        ],
    )
    def test_wrong_timestamp(timestamp):
        with pytest.raises(OSError):
>           from_utc_timestamp(timestamp)
E           Failed: DID NOT RAISE <class 'OSError'>

tests/test_time.py:121: Failed
____________________________________________________________________________________________________________________ test_wrong_timestamp[1523443804214.0] _____________________________________________________________________________________________________________________

timestamp = 1523443804214.0

    @pytest.mark.parametrize(
        "timestamp",
        [
            2 ** 60,
            -43201,
            1523443804214.0,
        ],
    )
    def test_wrong_timestamp(timestamp):
        with pytest.raises(OSError):
>           from_utc_timestamp(timestamp)

tests/test_time.py:121: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

timestamp = 1523443804214.0

    def from_utc_timestamp(timestamp: int) -> datetime:
>       return datetime.fromtimestamp(timestamp, timezone.utc)
E       ValueError: year 50246 is out of range

together_bot/time.py:72: ValueError
=========================================================================================================================== short test summary info ============================================================================================================================
FAILED tests/test_time.py::test_from_kst_time_string - AssertionError: assert datetime.datetime(2020, 12, 1, 6, 59, tzinfo=datetime.timezone(datetime.timedelta(seconds=32400))) == datetime.datetime(2020, 11, 30, 21,  [...]

2021-06-14 06:23 UTC, WraithKim commented
> Docker에서 pytest 실행 시 테스트 실패
> 
> 출력

여기서 맨 앞의 2개의 테스트인 kst_time의 timezone을 변경하는 테스트는 원인 파악이 어렵지 않다고 생각해서 확인하고 수정할 예정.  
나머지 4개는 예상되는 원인이 생각나지 않음. 그래서 어려운 문제고, 당장 PR에서는 제거하고 나중에 고려하든지 draft로 남기든지 해서 해결을 미루는 걸로 결정함.

2021-06-22 12:52 UTC, lyuha requested changes

2021-06-22 12:52 UTC, lyuha commented on together_bot/time.py
>  def from_kst_time_string(kst_time: str):
여기에 type hint 빠짐.
다른 곳은 있는데, 여기에는 타입 힌트가 없는 이유가 있나요?

2021-06-22 12:52 UTC, lyuha commented on together_bot/time.py
> +            logging.error("wrong type: " + type(kst_time))
```pyi
>>> dt = datetime.datetime.now() 
>>> print("string" + type(dt))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
```
이 부분 python interpreter에서 에러남

2021-06-23 01:12 UTC, WraithKim commented on together_bot/time.py
>  def from_kst_time_string(kst_time: str):
추가함

2021-06-23 01:13 UTC, WraithKim commented on together_bot/time.py
> +            logging.error("wrong type: " + type(kst_time))
수정함

2021-06-23 01:37 UTC, merged