Feature: add `role get` command that can give role to user
team-play-together/together-bot pull request #8
Opened 2020-09-15 14:17 UTC by lyuha

2020-09-17 11:50 UTC, WraithKim requested changes
난 평일 출근이 싫다.

2020-09-17 11:50 UTC, WraithKim commented on together_bot/role.py
> +        if role is not None:
찾는 role이 없으면 어케됨?

2020-09-17 11:50 UTC, WraithKim commented on together_bot/role.py
> +                    await user.add_roles(role)
지금은 리액션에 대답하는 명령이 get밖에 없어서 리액션에 대답하는 이벤트에 role 추가/제거를 넣어둔거임?

2020-09-17 12:18 UTC, lyuha commented on together_bot/role.py
> +                    await user.add_roles(role)
ㅇ. 그리고 reaction이 추가된 메시지가 조건이 충족될 때 role을 부여함

- Guild(서버) 일 것
- 리액션을 추가한 메시지가 guild -> message.id 맵핑에 이미 있어야 함.

2020-09-17 12:19 UTC, lyuha commented on together_bot/role.py
> +                f"Exists **_{role.name}_**, assing to role, "
Solve 2e7d2f8

2020-09-17 12:20 UTC, lyuha commented on together_bot/role.py
> +        if role is not None:
Return `None`. 그래서 아무것도 동작하지 않음.

2020-09-18 02:33 UTC, WraithKim approved these changes
done.

2020-09-18 02:35 UTC, merged